
id: gebied
object_type: gebied

sort_allowed_columns: &sort_allowed_columns
  - Object_ID
  - Title
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_columns

api:
  routers:
    - prefix: /gebieden
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: gebied_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_title
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: gebied_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: gebied_full
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: gebied_full
    - prefix: /gebied/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: gebied_static_post
            result_model: gebied_static_post_validated
    - prefix: /modules/{module_id}/object/gebied
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: gebied_patch
            response_model: gebied_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: gebied_extended
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: gebied_full
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: gebied_full
    - prefix: /modules/object/gebied
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
    - prefix: /revisions/{module_id}/gebied/version/{object_uuid}
      endpoints:
        - resolver: module_object_version
          resolver_data:
            response_model: gebied_full
            minimum_status: 'Ontwerp GS Concept'
            require_auth: False

fields:
  title:
    name: Title
    type: str
    column: title
  area_uuid:
    name: Area_UUID
    type: uuid
    column: area_uuid

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  gebied_minimal:
    name: GebiedMinimal
    fields:
      object_type:
      object_id:
      uuid:
      title:
  gebied_basic:
    name: GebiedBasic
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      area_uuid:
      start_validity:
      end_validity:
  gebied_extended:
    name: GebiedExtended
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      area_uuid:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  gebied_full:
    name: GebiedFull
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      area_uuid:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
      - area_basic
    services:
      next_object_version:
        to_field: Next_Version
      public_revisions:
        to_field: Public_Revisions
      foreign_keys_extender:
        fields_map:
          - to_field: Area
            model_id: area_basic
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  gebied_patch:
    name: GebiedPatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
  gebied_static_post:
    name: GebiedStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  gebied_static_post_validated:
    name: GebiedStaticPostValidated
    static_only: true
    root_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
  gebied_uuid:
    name: GebiedUUID
    fields:
      object_id:
      uuid:
